# Generated by Django 3.2 on 2021-04-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
