# Generated by Django 3.2 on 2021-04-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_new_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('order', models.SmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation link',
                'verbose_name_plural': 'Navigation links',
                'db_table': 'navigation_links',
            },
        ),
    ]
